[project]
name = "pbsg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.9.0",
    "pylance>=0.36.0",
]
